#
# Module manifest for module 'Posh-Nessus'
#
# Generated by: Tenable Network Security
#
# Generated on: 2/2/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\Posh-Nessus.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '7cb6d5c3-230b-47ea-9ace-55d034ff3102'

# Author of this module
Author = 'Tenable Network Security'

# Company or vendor of this module
CompanyName = 'Tenable Network Security'

# Copyright statement for this module
Copyright = 'Tenable Network Security'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('.\Format\Nessus.Session.ps1xml',
                      '.\Format\Nessus.ServerStatus.ps1xml',
                      '.\Format\Nessus.Scan.HostDetails.ps1xml',
                      '.\Format\Nessus.PluginFamily.ps1xml',
                      '.\Format\Nessus.PluginFamilyDetails.ps1xml',
                      '.\Format\Nessus.PolicyCopy.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*-Nessus*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

